version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "ap-southeast-1"
    AWS_DEFAULT_OUTPUT: "json"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

      - REPOSITORY_URI_APP=657750027235.dkr.ecr.ap-southeast-1.amazonaws.com/ocr-template-creator
      - COMMIT_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo ">>>>>> BUILD IMAGES"
      - docker build . -t $CODEBUILD_RESOLVED_SOURCE_VERSION:$COMMIT_TAG
      - docker build . -t $CODEBUILD_RESOLVED_SOURCE_VERSION:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo ">>>>>> PUSH IMAGES"
      - docker push $CODEBUILD_RESOLVED_SOURCE_VERSION:$COMMIT_TAG
      - docker push $CODEBUILD_RESOLVED_SOURCE_VERSION:latest
cache:
  paths:
    - 'node_modules/**'
artifacts:
  files:
    - '**/*'
  name: ocr-template-creator
  discard-paths: yes
